export default {
  UPDATE_SEARCH_TERM: 'UPDATE_SEARCH_TERM',
  EXECUTE_SEARCH: 'EXECUTE_SEARCH',
  GET_MOVIE: 'GET_MOVIE',
  DESELECT_MOVIE: 'DESELECT_MOVIE',
  UPDATE_RESULTS: 'UPDATE_RESULTS',
  SELECT_MOVIE: 'SELECT_MOVIE',
};
